/// <mls fileReference="_102025_/l2/designSystem.ts" enhancement="_blank" />

import { IDesignSystemTokens } from '/_102029_/l2/designSystemBase.js';

/**
 * Project design system — ROLE-BASED token vocabulary.
 * Migrated from the old family-based model (text-primary-color, bg-secondary-color,
 * grey-color) to the canonical vocabulary of _102029_/l2/designSystemBase.ts
 * (DEFAULT_TOKENS_TEMPLATE). See TASK-102025-ds-tokens-por-papel.md.
 *
 * Naming rules (color):
 *  - The name says WHERE the token is used; never infer it from the value.
 *  - Pairs travel together: whoever paints with button-primary-bg writes the
 *    label with button-primary-text; status-error-bg goes with status-error-text;
 *    nav-bg with nav-text; tooltip-bg with tooltip-text. Holds for every
 *    <role>-bg / <role>-text pair.
 *  - Surfaces: page-bg (page background) > surface-bg (cards, panels, modals) >
 *    surface-alt-bg (zebra rows, row hover, skeleton, section headers). Text on
 *    surfaces: text-strong (titles), text-default (body), text-muted
 *    (secondary/placeholder).
 *  - Navigation (sidebar/topbar): nav-bg + nav-text; the active item uses
 *    nav-active-bg + nav-active-text.
 *  - Modal overlay: overlay-backdrop-bg behind, surface-bg on the modal.
 *  - Charts: series use chart-series-1..6 ALWAYS in this fixed order (the order
 *    IS the colour-blindness safeguard — never shuffle, never generate new
 *    colours); labels and axes use the text-* tokens, never the series colour;
 *    status-* are reserved for state and never become a chart series.
 *  - Every base colour token has -hover, -focus and -disabled variants (on
 *    chart-series, -disabled is the series dimmed by the legend).
 *  - Night mode: every key has a _dark- twin (same name). The compiler emits the
 *    dark block automatically; pages only ever use the base name.
 *
 * Where the values came from:
 *  - Roles with an origin in the old DS inherited the 102025 value (text greys,
 *    surfaces, the grey-* border scale, the #1890FF brand accent, state colours).
 *  - button-primary-bg comes from the old info-color (#0a6dc9): that is what
 *    painted .btn-save / button.activate / button.edit, not active-color.
 *    active-color (#1890FF) was selection and focus, so it feeds selected-text,
 *    selected-border, focus-ring and nav-active-text.
 *  - In dark, text-strong comes from _dark-text-primary-color-LIGHTER and
 *    text-muted from _dark-text-primary-color-DARKER: in the dark the lightest
 *    tone is the title and the darkest is the secondary text — an inversion the
 *    family-based model could not express.
 *  - status-*-bg did not exist: it is the `fade(<state colour>, 10%)` the .less
 *    files applied inline, now resolved as a token (and therefore theme-reactive).
 *  - Roles with no origin (page-bg, input-bg, button-secondary-*, selected-bg,
 *    status-neutral-*, nav-* other than nav-active-text, overlay-backdrop-bg,
 *    tooltip-*, chart-series-*) kept the template defaults.
 */
export const tokens: IDesignSystemTokens[] = [
    {
        themeName: "Default",
        description: "Tema padrão do projeto",
        color: {
            "page-bg": "#eef1f5",
            "page-bg-hover": "#dde0e4",
            "page-bg-focus": "#cfd2d5",
            "page-bg-disabled": "#eef1f5",
            "surface-bg": "#ffffff",
            "surface-bg-hover": "#f2f2f2",
            "surface-bg-focus": "#e6e6e6",
            "surface-bg-disabled": "#d9d9d9",
            "surface-alt-bg": "#fafafa",
            "surface-alt-bg-hover": "#f5f5f5",
            "surface-alt-bg-focus": "#eeeeee",
            "surface-alt-bg-disabled": "#e0e0e0",
            "input-bg": "#ffffff",
            "input-bg-hover": "#ededed",
            "input-bg-focus": "#dedede",
            "input-bg-disabled": "#f6f7fa",
            "text-strong": "#000000",
            "text-strong-hover": "#1a1a1a",
            "text-strong-focus": "#0d0d0d",
            "text-strong-disabled": "#262626",
            "text-default": "#403f3f",
            "text-default-hover": "#4b4a4a",
            "text-default-focus": "#353434",
            "text-default-disabled": "#525151",
            "text-muted": "#535353",
            "text-muted-hover": "#5f5f5f",
            "text-muted-focus": "#4a4a4a",
            "text-muted-disabled": "#696969",
            "border-default": "#E6E6E6",
            "border-default-hover": "#D3D3D3",
            "border-default-focus": "#C0C0C0",
            "border-default-disabled": "#F2F2F2",
            "border-subtle": "#F2F2F2",
            "border-subtle-hover": "#E6E6E6",
            "border-subtle-focus": "#D3D3D3",
            "border-subtle-disabled": "#F9FAFB",
            "button-primary-bg": "#0a6dc9",
            "button-primary-bg-hover": "#1b7edb",
            "button-primary-bg-focus": "#006ab3",
            "button-primary-bg-disabled": "#66a8e1",
            "button-primary-text": "#ffffff",
            "button-primary-text-hover": "#ededed",
            "button-primary-text-focus": "#dedede",
            "button-primary-text-disabled": "#f6f7fa",
            "button-secondary-bg": "#ffffff",
            "button-secondary-bg-hover": "#ededed",
            "button-secondary-bg-focus": "#dedede",
            "button-secondary-bg-disabled": "#f6f7fa",
            "button-secondary-text": "#2f3a48",
            "button-secondary-text-hover": "#2c3643",
            "button-secondary-text-focus": "#29323f",
            "button-secondary-text-disabled": "#989fa7",
            "button-secondary-border": "#c3cedb",
            "button-secondary-border-hover": "#b5c0cc",
            "button-secondary-border-focus": "#aab3bf",
            "button-secondary-border-disabled": "#dbe1e9",
            "button-danger-bg": "#FF4D4F",
            "button-danger-bg-hover": "#ff6666",
            "button-danger-bg-focus": "#e63e3e",
            "button-danger-bg-disabled": "#ff9999",
            "button-danger-text": "#ffffff",
            "button-danger-text-hover": "#ededed",
            "button-danger-text-focus": "#dedede",
            "button-danger-text-disabled": "#f6f7fa",
            "link-text": "#1890FF",
            "link-text-hover": "#1a99ff",
            "link-text-focus": "#0e80cc",
            "link-text-disabled": "#66b3ff",
            "focus-ring": "#1890FF",
            "focus-ring-hover": "#1a99ff",
            "focus-ring-focus": "#0e80cc",
            "focus-ring-disabled": "#66b3ff",
            "selected-bg": "#e3f1ff",
            "selected-bg-hover": "#d3e0ed",
            "selected-bg-focus": "#c5d2de",
            "selected-bg-disabled": "#e9f1fa",
            "selected-text": "#1890FF",
            "selected-text-hover": "#1a99ff",
            "selected-text-focus": "#0e80cc",
            "selected-text-disabled": "#66b3ff",
            "selected-border": "#1890FF",
            "selected-border-hover": "#1a99ff",
            "selected-border-focus": "#0e80cc",
            "selected-border-disabled": "#66b3ff",
            "status-success-bg": "#eef9e8",
            "status-success-bg-hover": "#e5f6dd",
            "status-success-bg-focus": "#dcf3d1",
            "status-success-bg-disabled": "#f5fbf1",
            "status-success-text": "#52C41A",
            "status-success-text-hover": "#66d93f",
            "status-success-text-focus": "#4ca610",
            "status-success-text-disabled": "#8cd78e",
            "status-error-bg": "#ffeded",
            "status-error-bg-hover": "#ffe4e5",
            "status-error-bg-focus": "#ffdbdc",
            "status-error-bg-disabled": "#fff4f4",
            "status-error-text": "#FF4D4F",
            "status-error-text-hover": "#ff6666",
            "status-error-text-focus": "#e63e3e",
            "status-error-text-disabled": "#ff9999",
            "status-warning-bg": "#fff7e8",
            "status-warning-bg-hover": "#fef3dc",
            "status-warning-bg-focus": "#feefd0",
            "status-warning-bg-disabled": "#fffaf1",
            "status-warning-text": "#FAAD14",
            "status-warning-text-hover": "#fbbd34",
            "status-warning-text-focus": "#e09a0e",
            "status-warning-text-disabled": "#fdd55e",
            "status-info-bg": "#e7f0fa",
            "status-info-bg-hover": "#dae9f7",
            "status-info-bg-focus": "#cee2f4",
            "status-info-bg-disabled": "#f0f6fc",
            "status-info-text": "#0a6dc9",
            "status-info-text-hover": "#1b7edb",
            "status-info-text-focus": "#006ab3",
            "status-info-text-disabled": "#66a8e1",
            "status-neutral-bg": "#e9edf2",
            "status-neutral-bg-hover": "#d9dce1",
            "status-neutral-bg-focus": "#cbced3",
            "status-neutral-bg-disabled": "#eceff4",
            "status-neutral-text": "#46535f",
            "status-neutral-text-hover": "#414d58",
            "status-neutral-text-focus": "#3d4853",
            "status-neutral-text-disabled": "#a2aab2",
            "nav-bg": "#1c2430",
            "nav-bg-hover": "#1a212d",
            "nav-bg-focus": "#181f2a",
            "nav-bg-disabled": "#90959c",
            "nav-text": "#c9d3df",
            "nav-text-hover": "#bbc4cf",
            "nav-text-focus": "#afb8c2",
            "nav-text-disabled": "#dde4eb",
            "nav-active-bg": "#2e3d52",
            "nav-active-bg-hover": "#2b394c",
            "nav-active-bg-focus": "#283547",
            "nav-active-bg-disabled": "#98a0ac",
            "nav-active-text": "#1890FF",
            "nav-active-text-hover": "#1a99ff",
            "nav-active-text-focus": "#0e80cc",
            "nav-active-text-disabled": "#66b3ff",
            "overlay-backdrop-bg": "rgba(9, 14, 20, 0.55)",
            "overlay-backdrop-bg-hover": "rgba(9, 14, 20, 0.55)",
            "overlay-backdrop-bg-focus": "rgba(9, 14, 20, 0.55)",
            "overlay-backdrop-bg-disabled": "rgba(9, 14, 20, 0.55)",
            "tooltip-bg": "#1c2430",
            "tooltip-bg-hover": "#1a212d",
            "tooltip-bg-focus": "#181f2a",
            "tooltip-bg-disabled": "#90959c",
            "tooltip-text": "#f0f4f8",
            "tooltip-text-hover": "#dfe3e7",
            "tooltip-text-focus": "#d1d4d8",
            "tooltip-text-disabled": "#eff2f6",
            "chart-series-1": "#2a78d6",
            "chart-series-1-hover": "#2770c7",
            "chart-series-1-focus": "#2568ba",
            "chart-series-1-disabled": "#96bbe7",
            "chart-series-2": "#1baf7a",
            "chart-series-2-hover": "#19a371",
            "chart-series-2-focus": "#17986a",
            "chart-series-2-disabled": "#8fd3be",
            "chart-series-3": "#eda100",
            "chart-series-3-hover": "#dc9600",
            "chart-series-3-focus": "#ce8c00",
            "chart-series-3-disabled": "#eecd87",
            "chart-series-4": "#008300",
            "chart-series-4-hover": "#007a00",
            "chart-series-4-focus": "#007200",
            "chart-series-4-disabled": "#83c087",
            "chart-series-5": "#4a3aa7",
            "chart-series-5-hover": "#45369b",
            "chart-series-5-focus": "#403291",
            "chart-series-5-disabled": "#a49fd2",
            "chart-series-6": "#e34948",
            "chart-series-6-hover": "#d34443",
            "chart-series-6-focus": "#c5403f",
            "chart-series-6-disabled": "#e9a5a7",
            "_dark-page-bg": "#0d1117",
            "_dark-page-bg-hover": "#1e2227",
            "_dark-page-bg-focus": "#2c3035",
            "_dark-page-bg-disabled": "#0d1117",
            "_dark-surface-bg": "#0d1117",
            "_dark-surface-bg-hover": "#1a1f24",
            "_dark-surface-bg-focus": "#0a0e13",
            "_dark-surface-bg-disabled": "#2b3036",
            "_dark-surface-alt-bg": "#161b22",
            "_dark-surface-alt-bg-hover": "#1f2329",
            "_dark-surface-alt-bg-focus": "#0f1418",
            "_dark-surface-alt-bg-disabled": "#2c3238",
            "_dark-input-bg": "#10151c",
            "_dark-input-bg-hover": "#21252c",
            "_dark-input-bg-focus": "#2f333a",
            "_dark-input-bg-disabled": "#0e1319",
            "_dark-text-strong": "#FFFFFF",
            "_dark-text-strong-hover": "#f2f2f2",
            "_dark-text-strong-focus": "#e6e6e6",
            "_dark-text-strong-disabled": "#d9d9d9",
            "_dark-text-default": "#e6edf3",
            "_dark-text-default-hover": "#d1d9e4",
            "_dark-text-default-focus": "#c3cfd8",
            "_dark-text-default-disabled": "#b0b8c4",
            "_dark-text-muted": "#8d96a0",
            "_dark-text-muted-hover": "#a1aab0",
            "_dark-text-muted-focus": "#7a828a",
            "_dark-text-muted-disabled": "#b1b7bd",
            "_dark-border-default": "#575757",
            "_dark-border-default-hover": "#6D6D6D",
            "_dark-border-default-focus": "#969494",
            "_dark-border-default-disabled": "#414141",
            "_dark-border-subtle": "#414141",
            "_dark-border-subtle-hover": "#575757",
            "_dark-border-subtle-focus": "#6D6D6D",
            "_dark-border-subtle-disabled": "#2B2B2B",
            "_dark-button-primary-bg": "#0b81ef",
            "_dark-button-primary-bg-hover": "#1a95f6",
            "_dark-button-primary-bg-focus": "#0073d8",
            "_dark-button-primary-bg-disabled": "#66b3ef",
            "_dark-button-primary-text": "#06121f",
            "_dark-button-primary-text-hover": "#17232f",
            "_dark-button-primary-text-focus": "#26313c",
            "_dark-button-primary-text-disabled": "#0a111b",
            "_dark-button-secondary-bg": "#1e2530",
            "_dark-button-secondary-bg-hover": "#2e343e",
            "_dark-button-secondary-bg-focus": "#3b414b",
            "_dark-button-secondary-bg-disabled": "#151a22",
            "_dark-button-secondary-text": "#d7dee6",
            "_dark-button-secondary-text-hover": "#dae0e8",
            "_dark-button-secondary-text-focus": "#dce2e9",
            "_dark-button-secondary-text-disabled": "#686d74",
            "_dark-button-secondary-border": "#3a4351",
            "_dark-button-secondary-border-hover": "#48505d",
            "_dark-button-secondary-border-focus": "#545b68",
            "_dark-button-secondary-border-disabled": "#212831",
            "_dark-button-danger-bg": "#f9676a",
            "_dark-button-danger-bg-hover": "#ff7b7f",
            "_dark-button-danger-bg-focus": "#e5565e",
            "_dark-button-danger-bg-disabled": "#ff9b9e",
            "_dark-button-danger-text": "#1f0708",
            "_dark-button-danger-text-hover": "#2f1819",
            "_dark-button-danger-text-focus": "#3c2728",
            "_dark-button-danger-text-disabled": "#150c10",
            "_dark-link-text": "#0b81ef",
            "_dark-link-text-hover": "#1a95f6",
            "_dark-link-text-focus": "#0073d8",
            "_dark-link-text-disabled": "#66b3ef",
            "_dark-focus-ring": "#0b81ef",
            "_dark-focus-ring-hover": "#1a95f6",
            "_dark-focus-ring-focus": "#0073d8",
            "_dark-focus-ring-disabled": "#66b3ef",
            "_dark-selected-bg": "#123351",
            "_dark-selected-bg-hover": "#23415d",
            "_dark-selected-bg-focus": "#314e68",
            "_dark-selected-bg-disabled": "#0f2031",
            "_dark-selected-text": "#0b81ef",
            "_dark-selected-text-hover": "#1a95f6",
            "_dark-selected-text-focus": "#0073d8",
            "_dark-selected-text-disabled": "#66b3ef",
            "_dark-selected-border": "#0b81ef",
            "_dark-selected-border-hover": "#1a95f6",
            "_dark-selected-border-focus": "#0073d8",
            "_dark-selected-border-disabled": "#66b3ef",
            "_dark-status-success-bg": "#1c341b",
            "_dark-status-success-bg-hover": "#22401c",
            "_dark-status-success-bg-focus": "#274c1d",
            "_dark-status-success-bg-disabled": "#162519",
            "_dark-status-success-text": "#63d42b",
            "_dark-status-success-text-hover": "#75d93d",
            "_dark-status-success-text-focus": "#55b825",
            "_dark-status-success-text-disabled": "#8ade5f",
            "_dark-status-error-bg": "#372026",
            "_dark-status-error-bg-hover": "#46262b",
            "_dark-status-error-bg-focus": "#542b30",
            "_dark-status-error-bg-disabled": "#251a1f",
            "_dark-status-error-text": "#f9676a",
            "_dark-status-error-text-hover": "#ff7b7f",
            "_dark-status-error-text-focus": "#e5565e",
            "_dark-status-error-text-disabled": "#ff9b9e",
            "_dark-status-warning-bg": "#362d1b",
            "_dark-status-warning-bg-hover": "#43361c",
            "_dark-status-warning-bg-focus": "#50401d",
            "_dark-status-warning-bg-disabled": "#242119",
            "_dark-status-warning-text": "#eead2b",
            "_dark-status-warning-text-hover": "#f2b73d",
            "_dark-status-warning-text-focus": "#d69c1f",
            "_dark-status-warning-text-disabled": "#f5cd5c",
            "_dark-status-info-bg": "#0d253e",
            "_dark-status-info-bg-hover": "#0d2c4b",
            "_dark-status-info-bg-focus": "#0c3358",
            "_dark-status-info-bg-disabled": "#0d1c2d",
            "_dark-status-info-text": "#0b81ef",
            "_dark-status-info-text-hover": "#1a95f6",
            "_dark-status-info-text-focus": "#0073d8",
            "_dark-status-info-text-disabled": "#66b3ef",
            "_dark-status-neutral-bg": "#2a323d",
            "_dark-status-neutral-bg-hover": "#39404b",
            "_dark-status-neutral-bg-focus": "#464d56",
            "_dark-status-neutral-bg-disabled": "#1a2028",
            "_dark-status-neutral-text": "#b0bcc9",
            "_dark-status-neutral-text-hover": "#b6c1cd",
            "_dark-status-neutral-text-focus": "#bac5d0",
            "_dark-status-neutral-text-disabled": "#565e67",
            "_dark-nav-bg": "#10151c",
            "_dark-nav-bg-hover": "#21252c",
            "_dark-nav-bg-focus": "#2f333a",
            "_dark-nav-bg-disabled": "#0e1319",
            "_dark-nav-text": "#96a3b3",
            "_dark-nav-text-hover": "#9da9b8",
            "_dark-nav-text-focus": "#a4afbd",
            "_dark-nav-text-disabled": "#4b535d",
            "_dark-nav-active-bg": "#123351",
            "_dark-nav-active-bg-hover": "#23415d",
            "_dark-nav-active-bg-focus": "#314e68",
            "_dark-nav-active-bg-disabled": "#0f2031",
            "_dark-nav-active-text": "#0b81ef",
            "_dark-nav-active-text-hover": "#1a95f6",
            "_dark-nav-active-text-focus": "#0073d8",
            "_dark-nav-active-text-disabled": "#66b3ef",
            "_dark-overlay-backdrop-bg": "rgba(0, 0, 0, 0.65)",
            "_dark-overlay-backdrop-bg-hover": "rgba(0, 0, 0, 0.65)",
            "_dark-overlay-backdrop-bg-focus": "rgba(0, 0, 0, 0.65)",
            "_dark-overlay-backdrop-bg-disabled": "rgba(0, 0, 0, 0.65)",
            "_dark-tooltip-bg": "#2a323d",
            "_dark-tooltip-bg-hover": "#39404b",
            "_dark-tooltip-bg-focus": "#464d56",
            "_dark-tooltip-bg-disabled": "#1a2028",
            "_dark-tooltip-text": "#f0f4f8",
            "_dark-tooltip-text-hover": "#f1f5f8",
            "_dark-tooltip-text-focus": "#f2f5f9",
            "_dark-tooltip-text-disabled": "#73777c",
            "_dark-chart-series-1": "#3987e5",
            "_dark-chart-series-1-hover": "#478fe7",
            "_dark-chart-series-1-focus": "#5397e8",
            "_dark-chart-series-1-disabled": "#214674",
            "_dark-chart-series-2": "#199e70",
            "_dark-chart-series-2-hover": "#29a57a",
            "_dark-chart-series-2-focus": "#37ab83",
            "_dark-chart-series-2-disabled": "#12503f",
            "_dark-chart-series-3": "#c98500",
            "_dark-chart-series-3-hover": "#cd8e12",
            "_dark-chart-series-3-focus": "#d09521",
            "_dark-chart-series-3-disabled": "#62450d",
            "_dark-chart-series-4": "#008300",
            "_dark-chart-series-4-hover": "#128c12",
            "_dark-chart-series-4-focus": "#219321",
            "_dark-chart-series-4-disabled": "#07440d",
            "_dark-chart-series-5": "#9085e9",
            "_dark-chart-series-5-hover": "#988eeb",
            "_dark-chart-series-5-focus": "#9e95ec",
            "_dark-chart-series-5-disabled": "#484575",
            "_dark-chart-series-6": "#e66767",
            "_dark-chart-series-6-hover": "#e87272",
            "_dark-chart-series-6-focus": "#e97b7b",
            "_dark-chart-series-6-disabled": "#6f383b"
        },
        global: {
            "breakpoint-small": "544px",
            "breakpoint-medium": "768px",
            "breakpoint-large": "1012px",
            "transition-slow": "0.5s",
            "transition-normal": "0.3s",
            "transition-fast": "0.2s",
            "space-base-unit": "0.25rem",
            "space-8": "calc(@space-base-unit * 2)",
            "space-16": "calc(@space-base-unit * 4)",
            "space-24": "calc(@space-base-unit * 6)",
            "space-32": "calc(@space-base-unit * 8)",
            "space-40": "calc(@space-base-unit * 10)",
            "space-48": "calc(@space-base-unit * 12)",
            "space-64": "calc(@space-base-unit * 16)",
            "radius-small": "6px",
            "radius-medium": "10px",
            "radius-large": "14px",
            "radius-pill": "999px",
            "shadow-small": "0 1px 2px rgba(15, 23, 42, 0.06)",
            "shadow-medium": "0 4px 12px rgba(15, 23, 42, 0.10)"
        },
        typography: {
            "font-base-unit": ".25rem",
            "font-family-primary": "'Charlie Display', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
            "font-family-secondary": "serif",
            "font-size-12": "calc(@font-base-unit * 3)",
            "font-size-16": "calc(@font-base-unit * 4)",
            "font-size-20": "calc(@font-base-unit * 5)",
            "font-size-24": "calc(@font-base-unit * 6)",
            "font-size-40": "calc(@font-base-unit * 10)",
            "font-size-48": "calc(@font-base-unit * 12)",
            "font-size-64": "calc(@font-base-unit * 16)",
            "line-height-base-unit": "1",
            "line-height-small": "calc(@line-height-base-unit * 1.1)",
            "line-height-medium": "calc(@line-height-base-unit * 1.3)",
            "line-height-large": "calc(@line-height-base-unit * 1.5)",
            "font-weight-lighter": "100",
            "font-weight-light": "200",
            "font-weight-normal": "400",
            "font-weight-bold": "700",
            "font-weight-bolder": "900"
        },
    }
]
